/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/Fox.glb', draco('/draco-gltf/'))
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh material={materials.fox_material} geometry={nodes.fox.geometry} skeleton={nodes.fox.skeleton} />
    </group>
  )
}
